api/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^hello/$',
        views.HelloWorld.as_view()
        ),
    url(r'facebook/likes/locations$',
        views.FacebookLikesLocations.as_view(), name="likes"
        ),
]

social_me/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings

from . import views

urlpatterns = [
    url(
        r"login/$",
        views.LoginView.as_view(),
        name="login"
    ),
    url(
        r"logout/$",
        views.LogoutView.as_view(),
        name="logout"
    ),
    url(
        r'^$',
        views.IndexView.as_view(),
        name='index'
    ),
    url(
        r'^connect/',
        views.HomePageView.as_view(),
        name='connect'
    ),
    url(
        r'^privacy_policy/',
        views.PrivacyPolicyView.as_view(),
        name='privacy_policy'
    ),
    url(
        r'^admin/',
        admin.site.urls
    ),
    url(
        r'^dashboard/',
        include('dashboard.urls', namespace='dashboard')
    ),
    url(r'api/',
        include('api.urls', namespace='api')
        ),
    url(
        '',
        include('social.apps.django_app.urls', namespace='social')
    ),
    url(
        '',
        include('django.contrib.auth.urls', namespace='auth')
    ),
]

templates/connect.html
{% extends "layout.html" %}
{% load static %}


{% block title %}Connect your profiles{% endblock %}
{% block css %}
    <!-- Bootstrap tour -->
    <link href="{% static 'css/bootstrap-tour.min.css' %}" rel="stylesheet">
{% endblock %}

{%block content%}



     <div class="row">
            {% if messages %}
                <div class="col-md-6 col-md-offset-3 p-t-2">
                    <div class="alert alert-info">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                      <strong><i class="fa fa-info-circle" aria-hidden="true"></i></strong>
                        {% for message in messages %}
                            {{ message }}
                        {% endfor %}
                    </div>
                </div>
            {% endif %}


            <div class="row">
                <div class="col-xs-12 col-md-12">
                    <div class="text-center">
                        <h1>Hi there {{request.session.social_media.facebook.first_name }}</h1>
                        <p class="lead">
                            Connect your desired social media profiles below:
                        </p>
                    </div>
                </div>
            </div>

        <div id="connect-profiles" class="col-md-4 col-md-offset-4 col-xs-10 col-xs-offset-1">

            <!-- Facebook -->
            <div class="row p-t-1">
                <div >
                    <div class="no-hover-facebook">
                        <a class="btn btn-block btn-social btn-md btn-facebook">
                            <span class="fa fa-facebook" ></span>
                            <span class="success-color">Successfuly Connected</span>
                            <i class="fa fa-check-square" id="check_green" aria-hidden="true"></i>
                        </a>
                    </div>
                </div>
            </div>

            <!-- Instagram -->
            <div class="row p-t-1">
                <div>
                    {% if request.session.social_media.instagram %}
                        <div class="no-hover-instagram">
                            <a class="btn btn-block btn-social btn-md btn-instagram">
                                <span class="fa fa-instagram"></span>
                                <span class="success-color">Successfuly Connected</span>
                                <i class="fa fa-check-square" id="check_green" aria-hidden="true"></i>
                            </a>
                        </div>
                    {% else %}
                           <a href="{% url 'social:begin' 'instagram' %}" class="btn btn-block btn-social btn-md btn-instagram">
                                <span class="fa fa-instagram"></span>
                                Connect Instagram
                            </a>
                    {% endif %}
                </div>
            </div>

            <!-- LinkedIN -->
            <div class="row p-t-1">
                <div>
                    {% if request.session.social_media.linkedin %}
                        <div class="no-hover-linkedin">
                            <a class="btn btn-block btn-social btn-md btn-linkedin">
                                <span class="fa fa-linkedin"></span>
                                <span class="success-color">Successfuly Connected</span>
                                <i class="fa fa-check-square" id="check_green" aria-hidden="true"></i>
                            </a>
                        </div>
                    {% else %}
                    <a href="{% url 'social:begin' 'linkedin' %}" class="btn btn-block btn-social btn-md btn-linkedin">
                        <span class="fa fa-linkedin"></span>
                        Connect LinkedIn
                    </a>
                    {% endif %}
                </div>
            </div>

            <!-- Spotify -->
            <div class="row p-t-1 p-b-3">
                <div>
                    {% if request.session.social_media.spotify %}
                        <div class="no-hover-spotify">
                            <a class="btn btn-block btn-social btn-md spotify-button btn">
                                <span class="fa fa-spotify"></span>
                                Successfuly Connected
                                <i class="fa fa-check-square" id="check_white" aria-hidden="true"></i>
                            </a>
                        </div>
                    {% else %}
                    <a href="{% url 'social:begin' 'spotify' %}" class="btn btn-block btn-social btn-md btn-linkedin spotify-button">
                        <span class="fa fa-spotify"></span>
                        Connect Spotify
                    </a>
                    {% endif %}
                </div>
            </div>
         </div>

            <!-- Social Me Buton -->
            <div class="row p-t-5">
                <div class="col-xs-10 col-xs-offset-1 col-md-4 col-lg-offset-4" id="social-me">
                    <a href="{% url 'dashboard:social_me' %}" class="btn btn-block btn-lg btn-primary btn-more-info social-me">
                        <i class="fa fa-address-card" aria-hidden="true"></i>
                        Go to Social Me
                    </a>
                </div>
            </div>

            <!-- Dashboard button -->
            <div class="row p-t-1">
                <div class="col-xs-10 col-xs-offset-1 col-md-4 col-lg-offset-4" id="dashboard">
                    <a href="{% url 'dashboard:main' %}" class="btn btn-block btn-lg btn-primary btn-more-info" >
                        <i class="fa fa-users" aria-hidden="true"></i>
                        Go to dashboard of profiles
                    </a>
                </div>
            </div>

    </div>

    {% block javascript %}
        <!-- Social me Tour js -->
        <script src="{% static 'js/bootstrap-tour.min.js' %}"></script>
        <script src="{% static 'js/walk-through.js' %}"></script>
    {% endblock %}
{%endblock%}

templates/index.html
{% extends "layout.html" %}
{% load static %}

{% block title %}Social Me{% endblock %}

{%block content%}

    <div class="row">
        <div class="col-xs-12 col-md-6 col-lg-offset-3 ">
            <div class="text-center">
                <h1 class="header">Social Me</h1>
                <p class="p-t-2 lead">
                    <b>What?</b><br>
                    This site provides a free service, where you can view some of the information you provide to social medias.
                </p>
                <p class="lead">
                    <b>How?</b><br>
                    Choose the social media profiles you want to connect to the service.
                    The service will then retrieve your information from the chosen social media(s) and create a temporary Social Me.<br>
                </p>
                <p class="lead">
                    <b>Why?</b><br>
                    The main purpose of the project is to develop a service available for everyone,
                    to create a simple overview of which information we put on different platforms.
                    <br>
                </p>
                <p class="lead">
                    <b>What happens to my information?</b><br>
                    <u>None</u> of your information from social medias is stored. The information you provide is used to create a temporary 'Social Me', which only you can see<br><br>
                    <a href="{% url 'privacy_policy' %}">Read more about our Privacy Policy / Terms Of Use here</a>
                </p>

                <div class="col-md-6 col-md-offset-3 col-xs-8 col-xs-offset-2 p-t-2">
                    <a href="{% url 'auth:login' %}" class="btn btn-block btn-md btn-primary">
                      <i class="fa fa-sign-in" aria-hidden="true"></i>
                        Continue to log in
                    </a>
                </div>
            </div>
        </div>
    </div>
{%endblock%}

templates/layout.html
<!doctype html>
{% load static %}

<html lang="en">
    <head>
        <!-- meta stuff -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% endblock %}</title>

        <link rel="icon" type="image/png" href="{% static 'img/favicon.ico' %}">

        <!-- FONT -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:400,300,600" type="text/css">

        <!-- Social Buttons -->
        <link rel="stylesheet" href="{% static 'css/bootstrap-social.css' %}">

        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

        <!-- Custom stylesheet -->
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">

        <!-- sidebar.css -->
        <link rel="stylesheet" href="{% static 'css/simple-sidebar.css' %}">

        <!-- FontAwesome min css -->

        <script src="https://use.fontawesome.com/3e885a4d09.js"></script>

        {% block css %}{% endblock %}

    </head>
    <body>
        {% if user.is_authenticated %}
            <div id="wrapper">
                <!-- Sidebar -->
                <div id="sidebar-wrapper">

                    <ul class="sidebar-nav">
                        <li class="sidebar-brand">
                            <a href="#menu-toggle" id="menu-toggle">
                                <i class="fa fa-close" aria-hidden="true"></i>
                                Close
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'connect' %}">
                                <i class="fa fa-connectdevelop" aria-hidden="true"></i>
                                Connect
                            </a>
                        </li>
                        <li>
                            <a href="" class="social-me">
                                <i class="fa fa-address-card" aria-hidden="true"></i>
                                Social Me
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'dashboard:main' %}">
                                <i class="fa fa-users" aria-hidden="true"></i>
                                Dashboard
                            </a>
                        </li>
                        <li>
                            <a  href="" data-toggle="modal" data-target="#info-modal" id="menu-toggle">
                                <i class="fa fa-info-circle"  aria-hidden="true"></i>
                                Information
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'auth:logout' %}" id="menu-toggle">
                                <i class="fa fa-sign-out"  aria-hidden="true"></i>
                                Sign-out
                            </a>
                        </li>
                    </ul>
                </div>
                <!-- /#sidebar-wrapper END-->

                <!-- Contact Modal -->
                <div class="modal fade" id="info-modal" tabindex="-1" role="dialog" aria-labelledby="info-modal">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel"><i class="fa fa-info-circle"  aria-hidden="true"></i> Practical Information</h4>
                      </div>
                      <div class="modal-body">
                            Please feel free to send me an email at:<br>
                            <a href="mailto:niels@dawartz.dk"><i class="fa fa-envelope-o" aria-hidden="true"></i> niels@dawartz.dk</a><br><br>

                            You can at anytime read the Privacy Policy here:<br>
                            <a href="{% url 'privacy_policy' %}"><i class="fa fa-info" aria-hidden="true"></i> Privacy Policy</a><br>
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                      </div>
                    </div>
                  </div>
                </div>
                <!-- -->

                <!-- Loader Modal -->
                <div class="modal fade" id="loader-modal" tabindex="-1" role="dialog" aria-labelledby="loader-modal">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h4 class="modal-title text-center" id="myModalLabel"> Please wait...</h4>
                      </div>
                      <div class="modal-body text-center">
                          <div class="center-loader">
                            <div class="loader"><img src="{% static 'img/cube.gif' %}"></div>
                          </div>
                          We're loading your'e data from the connected social media's.
                          <br>(It takes about 30 seconds)
                      </div>
                      </div>
                    </div>
                  </div>
                <!-- -->
        {% endif %}

            <div id="page-content-wrapper" >
                 <div class="container-fluid">
                        <div class="row" id="menu-space">
                            <div class="menu-bar p-t-1">
                                {% if user.is_authenticated %}<!-- Menu bar -->
                                    <div class="col-md-3 fixed-hidden" id="menu-div">
                                        <a class="btn menu-bar-color" id="menu-toggle-2">
                                            <i class="fa fa-bars"  aria-hidden="true"></i>
                                        </a>
                                    </div><!-- Menu bar END -->
                                {% endif %}
                            </div>
                        </div>

                    <!-- body content -->
                    {% block content %}{% endblock %}
                    <div class="row p-t-5">

                    </div>
                </div>
            </div> <!-- page-content wrapper END -->
        </div> <!-- Wrapper END -->

        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

        <!-- Latest compiled and minified bootstrap JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

        <!-- main js -->
         <script src="{% static 'js/main.js' %}"></script>

        <!-- Minified Cookie Consent served from our CDN -->
        <script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/1.0.9/cookieconsent.min.js"></script>


        {% block javascript %}

        {% endblock %}
    </body>
</html>

templates/privacy_policy.html
{% extends "layout.html" %}
{% load static %}

{% block title %}Privacy Policy / Terms Of Service{% endblock %}

{%block content%}

    <div class="row">
        <div class="col-xs-12 col-md-8 col-md-offset-2 ">
            <div>
                <span class="text-center">
                <h2 class="header">Privacy Policy / Terms Of Service</h2><br>
                </span>
                <!-- Section 1 -->
                <div class="row ">
                    <span class="text-center">
                    <h3><strong>SECTION 1 - WHAT DO WE DO WITH YOUR INFORMATION?</strong></h3>
                    </span>
                    <div class="col-md-10 col-md-offset-1 col-xs-12 profile-well well md">
                        <p>
                            When you use our site, we do not collect the personal information you give us.<br><br>

                            All information are extracted through the social media profiles you connect, as for example facebook, instagram, linkedin and Spotify.
                            The information is used to provide you a view of your information and none of it is stored in a database.<br><br>

                            When you browse our website, we also automatically receive your computer’s internet protocol (IP) address in order to provide us with information that helps us learn about your browser and operating system.
                        </p>
                    </div>
                </div>

                <!-- Section 2 -->
                <div class="row ">
                    <span class="text-center">
                        <h3><strong>SECTION 2 - CONSENT</strong></h3>
                    </span>
                    <div class="col-md-10 col-md-offset-1 col-xs-12 profile-well well md">
                        <p>
                            <strong>How do you get my consent?</strong><br><br>

                            When you provide us with personal information to use the service, we we imply that you consent to our collecting it and using it for that specific reason only.<br><br>

                            If we ask for your personal information for a secondary reason, like marketing, we will either ask you directly for your expressed consent, or provide you with an opportunity to say no.
                        </p><br>

                        <p>
                            <strong>How do I withdraw my consent?</strong><br><br>

                            If after you opt-in, you change your mind, you may withdraw your consent for us to contact you, for the continued collection, use or disclosure of your information, at anytime, by contacting us at:
                            niels@dawartz.dk or mailing us at Åboulevard 12 2th, Copenhagen, 84, 2200, Denmark

                        </p>
                    </div>
                </div>

                <!-- Section 3 -->
                <div class="row ">
                    <span class="text-center">
                        <h3><strong>SECTION 3 - DISCLOSURE</strong></h3>
                    </span>
                    <div class="col-md-10 col-md-offset-1 col-xs-12 profile-well well md">
                        <p>
                            We may disclose your personal information if we are required by law to do so or if you violate our Terms of Service.
                        </p>
                    </div>
                </div>

                <!-- Section 4 -->
                <div class="row ">
                    <span class="text-center">
                        <h3><strong>SECTION 4 - THIRD-PARTY SERVICES</strong></h3>
                    </span>
                    <div class="col-md-10 col-md-offset-1 col-xs-12 profile-well well md">
                        <p>
                            The third-party providers used by us will only provide us with the information needed. We can’t extract and show your information without your consent.<br><br>

                            However, certain third-party service providers, such as facebook, instagram, linkedin and spotify, have their own privacy policies in respect to the information we are required to extract from them for viewing your information.<br>br>

                            For these providers, we recommend that you read their privacy policies so you can understand the manner in which your personal information will be handled by these providers.<br><br>

                            In particular, remember that certain providers may be located in or have facilities that are located in a different jurisdiction than either you or us. So if you elect to proceed with a transaction that involves the services of a third-party service provider, then your information may become subject to the laws of the jurisdiction(s) in which that service provider or its facilities are located.<br>br>

                            Once you leave our website or are redirected to a third-party website or application, you are no longer governed by this Privacy Policy or our website’s Terms of Service.<br><br>

                            <strong>Links</strong><br><br>

                            When you click on links, they may direct you away from our site. We are not responsible for the privacy practices of other sites and encourage you to read their privacy statements.
                        </p>
                    </div>
                </div>

                <!-- Section 5 -->
                <div class="row ">
                    <span class="text-center">
                        <h3><strong>SECTION 5 - SECURITY</strong></h3>
                    </span>
                    <div class="col-md-10 col-md-offset-1 col-xs-12 profile-well well md">
                        <p>
                            To protect your personal information, we take reasonable precautions and follow industry best practices to make sure it is not inappropriately lost, misused, accessed, disclosed, altered or destroyed.<br><br>

                            When you login to our service, the connection will be encrypted using secure socket layer technology (SSL).  Although no method of transmission over the Internet or electronic storage is 100% secure, we follow all the requirements and implement additional generally accepted industry standards.
                        </p>
                        <p>
                            <strong>COOKIES</strong><br><br>

                            Here is a list of cookies that we use. We’ve listed them here so you can choose if you want to opt-out of cookies or not.
                            <ul>
                                <li>_session_id, unique token, sessional, Allows us to store information about your session (referrer, landing page, etc).</li>
                                <li>_secure_session_id, unique token, sessional</li>
                                <li>csrftoken, protection against cross site scripting etc.</li>
                            </ul>

                            Please note, when you connect different Social Media profiles, they can use cookies. We are not responsible for any of these.
                        </p>
                    </div>
                </div>

                <!-- Section 6 -->
                <div class="row ">
                    <span class="text-center">
                        <h3><strong>SECTION 6 - AGE OF CONSENT</strong></h3>
                    </span>
                    <div class="col-md-10 col-md-offset-1 col-xs-12 profile-well well md">
                        <p>
                            By using this site, you represent that you are at least the age of majority in your state or province of residence, or that you are the age of majority in your state or province of residence and you have given us your consent to allow any of your minor dependents to use this site.
                        </p>
                    </div>
                </div>

                <!-- Section 7 -->
                <div class="row ">
                    <span class="text-center">
                        <h3><strong>SECTION 7 - CHANGES TO THIS PRIVACY POLICY</strong></h3>
                    </span>
                    <div class="col-md-10 col-md-offset-1 col-xs-12 profile-well well md">
                        <p>
                            We reserve the right to modify this privacy policy at any time, so please review it frequently. Changes and clarifications will take effect immediately upon their posting on the website.
                            If we make material changes to this policy, we will notify you here that it has been updated, so that you are aware of what information we collect, how we use it, and under what circumstances, if any, we use and/or disclose it.<br><br>

                            If our website is acquired or merged with another company, your information will not be transferred to the new owners.
                        </p>
                    </div>
                </div>

                <!-- questions and contact 7 -->
                <div class="row ">
                    <span class="text-center">
                        <h3><strong>QUESTIONS AND CONTACT INFORMATION</strong></h3>
                    </span>
                    <div class="col-md-10 col-md-offset-1 col-xs-12 profile-well well md">
                        <p>
                            If you would like to: register a complaint, or simply want more information contact us at:<br>
                            <a href="mailto:niels@dawartz.dk"><i class="fa fa-envelope-o" aria-hidden="true"></i> niels@dawartz.dk</a><br>
                            <i class="fa fa-map-marker" aria-hidden="true"></i> Åboulevard 12 2th, Copenhagen, 2200, Denmark
                        </p>
                    </div>
                </div>

        </div>
    </div>
{%endblock%}